import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

from modules.github_utils import get_latest_release_version  # noqa: E402


def main():
    latest_tag, latest_version = get_latest_release_version("shader-slang/slang")
    with open("modules/version.py", "w") as f:
        f.write(f"""# This file is auto-generated by {__file__}

SLANG_VERSION = {latest_version}
""")


if __name__ == "__main__":
    main()
